# Generated by Django 2.2.6 on 2021-06-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_group_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
