# Generated by Django 2.2.6 on 2021-07-01 20:11

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210701_0137'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(user=django.db.models.expressions.F('following')), name='user!=following'),
        ),
    ]
