# Generated by Django 2.2.6 on 2021-07-01 20:25

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210701_2313'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user!=following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('following')), name='user!=following'),
        ),
    ]
